In [8]:
#import torch
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.linear_model import LinearRegression

In [9]:
# Import data from excel file
yMassFlow = pd.read_excel("Data/TrainingData.xlsx", sheet_name="yMassFlow")
ySteamFlow = pd.read_excel("Data/TrainingData.xlsx", sheet_name="ySteamFlow")
xTotalSteamFlow = pd.read_excel("Data/TrainingData.xlsx", sheet_name="xTotalSteamFlow")
yMassFlow.head()

month  well1  well2  well3  well4  well5
0      0  127.3  117.3   57.7   47.4   35.7
1      1  123.8  113.8   56.5   46.5  141.8
2      2  122.4  112.4   55.8   45.9  145.1
3      3  121.5  111.5   55.3   45.6  144.3
4      4  120.8  110.8   55.0   45.3  143.8

In [10]:
ySteamFlow.head()

month  well1  well2  well3  well4  well5
0      0  20.53  26.80   5.87   2.82   4.89
1      1  20.18  26.64   5.76   2.77  19.42
2      2  20.19  27.00   5.69   2.74  19.94
3      3  20.34  27.57   5.65   2.72  19.92
4      4  20.59  28.26   5.63   2.71  19.96

In [11]:
xTotalSteamFlow.head()

month  totalSteamFlow
0      0           60.90
1      1           74.77
2      2           75.56
3      3           76.20
4      4           77.15

In [12]:
# Generate TFT data using a dictionary (format well: month# )
TFTs = {'well1': 3, 'well2': 5, 'well3': 7, 'well4': 8, 'well5': 10}

TFTdata = []
for i, element in enumerate(TFTs):
    month = TFTs.get(element)
    #print(i, element, month)
    mF = yMassFlow.loc[yMassFlow["month"]==month][element][month]
    sF = ySteamFlow.loc[ySteamFlow["month"]==month][element][month]
    p = [int(element[4:]), month, mF, sF, sF/mF] 
    TFTdata.append(p)
xTFT = pd.DataFrame(TFTdata, columns=['well', 'month', 'massFlow', 'steamFlow', 'dryness'])
xTFT

well  month  massFlow  steamFlow   dryness
0     1      3     121.5      20.34  0.167407
1     2      5     110.1      29.10  0.264305
2     3      7      54.3       5.58  0.102762
3     4      8      44.7       2.67  0.059732
4     5     10     141.2      20.90  0.148017

In [78]:
# Convert Y data to vector (well1, well2, ...) for regression
nMonths = len(ySteamFlow.index)
nWells = len(ySteamFlow.columns)-1
Y = ySteamFlow.loc[:, ySteamFlow.columns != "month"].to_numpy()
Y = Y.reshape([nMonths*nWells,1], order="F")[:,0] # Make vertical vector
Y[0:5]
#Y.shape

array([20.53, 20.18, 20.19, 20.34, 20.59])

In [77]:
# Convert X data to matrix
X = np.array([])
for i in range(nWells):
    X = np.append(X, xTotalSteamFlow["totalSteamFlow"].to_numpy())
X = X.reshape(-1, 1)
X[0:5]

array([[60.9 ],
       [74.77],
       [75.56],
       [76.2 ],
       [77.15]])

In [79]:
linreg = LinearRegression().fit(X, Y)

In [83]:
Xpred = linreg.predict(X)
Xpred

array([12.18106912, 14.95447854, 15.1124449 , 15.24041765, 15.4303772 ,
       15.6783244 , 16.00425499, 16.422166  , 16.96405061, 17.65790285,
       18.51971933, 19.6074877 , 20.45730673, 12.18106912, 14.95447854,
       15.1124449 , 15.24041765, 15.4303772 , 15.6783244 , 16.00425499,
       16.422166  , 16.96405061, 17.65790285, 18.51971933, 19.6074877 ,
       20.45730673, 12.18106912, 14.95447854, 15.1124449 , 15.24041765,
       15.4303772 , 15.6783244 , 16.00425499, 16.422166  , 16.96405061,
       17.65790285, 18.51971933, 19.6074877 , 20.45730673, 12.18106912,
       14.95447854, 15.1124449 , 15.24041765, 15.4303772 , 15.6783244 ,
       16.00425499, 16.422166  , 16.96405061, 17.65790285, 18.51971933,
       19.6074877 , 20.45730673, 12.18106912, 14.95447854, 15.1124449 ,
       15.24041765, 15.4303772 , 15.6783244 , 16.00425499, 16.422166  ,
       16.96405061, 17.65790285, 18.51971933, 19.6074877 , 20.45730673])

In [84]:
X

array([[ 60.9 ],
       [ 74.77],
       [ 75.56],
       [ 76.2 ],
       [ 77.15],
       [ 78.39],
       [ 80.02],
       [ 82.11],
       [ 84.82],
       [ 88.29],
       [ 92.6 ],
       [ 98.04],
       [102.29],
       [ 60.9 ],
       [ 74.77],
       [ 75.56],
       [ 76.2 ],
       [ 77.15],
       [ 78.39],
       [ 80.02],
       [ 82.11],
       [ 84.82],
       [ 88.29],
       [ 92.6 ],
       [ 98.04],
       [102.29],
       [ 60.9 ],
       [ 74.77],
       [ 75.56],
       [ 76.2 ],
       [ 77.15],
       [ 78.39],
       [ 80.02],
       [ 82.11],
       [ 84.82],
       [ 88.29],
       [ 92.6 ],
       [ 98.04],
       [102.29],
       [ 60.9 ],
       [ 74.77],
       [ 75.56],
       [ 76.2 ],
       [ 77.15],
       [ 78.39],
       [ 80.02],
       [ 82.11],
       [ 84.82],
       [ 88.29],
       [ 92.6 ],
       [ 98.04],
       [102.29],
       [ 60.9 ],
       [ 74.77],
       [ 75.56],
       [ 76.2 ],
       [ 77.15],
       [ 78.39],
       [ 80.02